name: Build Docker Images
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize submodules
        run: |
          git submodule update --init --recursive
      - name: Build images
        run: docker-compose build
        working-directory: dmoj
      - name: Test images
        run: |
          ./scripts/initialize
          docker-compose up -d
          sleep 10
          COMPOSE_EXEC_FLAGS="-T" ./scripts/copy_static
          COMPOSE_EXEC_FLAGS="-T" ./scripts/migrate
          COMPOSE_EXEC_FLAGS="-T" ./scripts/manage.py loaddata language_small
        working-directory: dmoj
      - name: Push images to Docker
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/dmoj-docker'
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
          docker push zydhanlinnar11/dmoj-base:latest
          docker push zydhanlinnar11/dmoj-site:latest
          docker push zydhanlinnar11/dmoj-celery:latest
          docker push zydhanlinnar11/dmoj-bridged:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
